FROM ubuntu:16.04

EXPOSE 8000
ENV FRONT_URL=http://localhost:5000

WORKDIR /mydir

RUN apt update
RUN apt install -y curl && curl -sL https://deb.nodesource.com/setup_10.x | bash && apt update && apt install -y nodejs
RUN node -v && npm -v

COPY ./backend-example-docker ./
RUN npm install

CMD ["/usr/bin/npm", "start"]
