FROM ruby:2.6.0

WORKDIR /mydir

RUN apt-get update && apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_10.x | bash && apt-get update && apt-get install -y nodejs
RUN apt-get install -y git
RUN git clone https://github.com/docker-hy/rails-example-project .
RUN gem install bundler:1.17.2
RUN bundle install

RUN rails db:migrate

ENV RAILS_LOG_TO_STDOUT=true
EXPOSE 3000

CMD ["rails", "s"]
