FROM ubuntu:16.04

WORKDIR /mydir

RUN apt update
RUN apt install -y curl && curl -sL https://deb.nodesource.com/setup_10.x | bash && apt update && apt install -y nodejs
RUN node -v && npm -v

COPY ./frontend-example-docker ./
RUN npm install

CMD ["/usr/bin/npm", "start"]
