FROM openjdk:16-slim

WORKDIR /mydir

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/docker-hy/spring-example-project . && ./mvnw package

EXPOSE 8080

CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]

